import XboxPin from '../../assets/pins/xbox-pin.png';
import AzurePin from '../../assets/pins/azure-pin.png';
import MahjongAiPin from '../../assets/pins/mahjong-ai-pin.png';
import FilmResearchPin from '../../assets/pins/film-research-pin.png';
import MagePin from '../../assets/pins/mage-pin.png';
import RcCarPin from '../../assets/pins/rc-car-pin.png';
import HappyEndingPin from '../../assets/pins/happy-ending-pin.png';
import type { BoardSide, PinConfig } from './types';

export const boardPins: Record<BoardSide, PinConfig[]> = {
  work: [
    {
      id: 'azure',
      image: AzurePin,
      size: 'md',
      initialRotate: 6,
      hoverRotate: -2,
      anchor: { left: 'clamp(28px, 8vw, 120px)', top: 'clamp(92px, 14vh, 124px)' },
      title: 'Azure Commerce',
      eyebrow: 'Professional',
      year: '2020 - 2021',
      subtitle: 'Infrastructure developer for billing data workflows',
      description: 'Built Azure commerce infrastructure for billing and data workflows, focusing on reliable ETL systems and operational correctness across Microsoft commerce surfaces.',
      bullets: ['Built Azure commerce billing workflows with reliable data pipelines', 'Designed high-throughput ETL systems with Azure Data Factory and Azure Functions', 'Focused on accuracy, reliability, and operational scale'],
    },
    {
      id: 'xbox',
      image: XboxPin,
      size: 'md',
      initialRotate: 10,
      hoverRotate: 5,
      anchor: { right: 'clamp(34px, 9vw, 132px)', bottom: 'clamp(58px, 8vh, 92px)' },
      title: 'Xbox Store',
      eyebrow: 'Professional',
      year: '2021 - Present',
      subtitle: 'Full Stack Developer',
      description: 'Built and shipped consumer store experiences for Xbox, working across product surfaces where reliability, performance, and user-facing polish directly affect player journeys.',
      bullets: ['Shipped Xbox store experiences across consumer-facing surfaces', 'Worked across frontend, backend, and service integration boundaries', 'Focused on reliable, performant, and polished commerce flows'],
    },
  ],
  research: [
    {
      id: 'paper',
      image: FilmResearchPin,
      size: 'md',
      initialRotate: -8,
      hoverRotate: -3,
      anchor: { left: 'clamp(28px, 8vw, 120px)', top: 'clamp(86px, 13vh, 118px)' },
      title: 'ICCV Oral Paper',
      eyebrow: 'Academia',
      year: '2019',
      subtitle: 'A Graph-Based Framework to Bridge Movies and Synopses',
      description: "Contributed to an ICCV Oral research project aligning movie segments with synopsis paragraphs across 328 films. Built tooling and preprocessing support for reviewing temporal alignment data.",
      bullets: ['Contributed to graph-based temporal alignment pipeline', 'Built React/Flask annotator for cross-platform dataset review', 'Implemented motion-energy preprocessing for segments and keyframes'],
      link: 'https://openaccess.thecvf.com/content_ICCV_2019/papers/Xiong_A_Graph-Based_Framework_to_Bridge_Movies_and_Synopses_ICCV_2019_paper.pdf',
      linkLabel: 'Read paper',
    },
    {
      id: 'mahjong',
      image: MahjongAiPin,
      size: 'sm',
      initialRotate: 6,
      hoverRotate: -2,
      anchor: { right: 'clamp(34px, 9vw, 132px)', top: 'clamp(88px, 13vh, 120px)' },
      title: 'Suphx Mahjong AI',
      eyebrow: 'Research',
      year: 'Summer 2017',
      subtitle: "The World's Strongest Mahjong AI",
      description: 'Contributed to early Suphx research, a Mahjong AI system that reached top-level performance in imperfect-information gameplay. Focused on reinforcement learning support workflows and analysis tools.',
      bullets: ['Researched reinforcement learning strategies for imperfect-information play', 'Built Qt tooling to inspect game logs and model decisions', 'Supported analysis workflows for a top-performing Mahjong AI system'],
      link: 'https://www.microsoft.com/en-us/research/project/suphx-mastering-mahjong-with-deep-reinforcement-learning/',
      linkLabel: 'View research',
    },
    {
      id: 'ironman',
      image: RcCarPin,
      size: 'md',
      initialRotate: -4,
      hoverRotate: 2,
      anchor: { right: 'clamp(26px, 7vw, 116px)', bottom: 'clamp(58px, 8vh, 92px)' },
      title: 'IRONMAN',
      eyebrow: 'Applied Research',
      year: '2020',
      subtitle: 'VR remote-driving rig',
      description: 'Built a VR remote-driving prototype for ROAR/Berkeley research, streaming camera feeds into an Oculus headset and translating wheel/pedal input into vehicle steering commands through a Jetson Nano.',
      bullets: ['Integrated RealSense and CSI camera streams into a Unity/Oculus rig', 'Mapped Logitech wheel and pedal input to remote vehicle controls', 'Demonstrated teleoperation workflow for training, data collection, and autonomy testing'],
      link: 'https://roar.berkeley.edu/',
      linkLabel: 'Visit project',
    },
  ],
  play: [
    {
      id: 'killstreak',
      image: MagePin,
      size: 'md',
      initialRotate: 7,
      hoverRotate: 2,
      anchor: { left: 'clamp(24px, 7vw, 112px)', top: 'clamp(84px, 13vh, 118px)' },
      title: 'KillStreak',
      eyebrow: 'College Project',
      year: '2019',
      subtitle: 'OpenGL MOBA with custom networking and physics',
      description: 'Built a team-based OpenGL MOBA for UCSD CSE 125, focused on real-time multiplayer gameplay, custom physics, and client-side rendering prediction.',
      bullets: ['Implemented coarse-mesh collision to improve server tick performance', 'Built screen-to-world mouse movement and client-side prediction', 'Contributed abilities, economy, UI, and pre-match gameplay systems'],
      link: 'https://github.com/roystormstout/cse125-sp19-group3',
      linkLabel: 'View code',
    },
    {
      id: 'happyEnding',
      image: HappyEndingPin,
      size: 'sm',
      initialRotate: -8,
      hoverRotate: -2,
      anchor: { right: 'clamp(26px, 8vw, 120px)', bottom: 'clamp(58px, 8vh, 90px)' },
      title: 'A Happy Ending',
      eyebrow: 'VR Game',
      year: '2018',
      subtitle: 'Polished all-campus VR competition winner',
      description: 'Built an award-winning Oculus VR narrative game for an all-campus competition, focusing on player locomotion, environmental interactions, and scripted story events.',
      bullets: ['Won Most Polished and Best Sound Effects', 'Implemented Oculus locomotion and interaction systems', 'Built trigger-driven doors, event scripting, and chaptered narrative flow'],
      link: 'https://github.com/roystormstout/A_Happy_Ending_VR_Game',
      linkLabel: 'View code',
    },
  ],
};