import XboxPin from '../../assets/pins/xbox-pin.png';
import AzurePin from '../../assets/pins/azure-pin.png';
import MahjongAiPin from '../../assets/pins/mahjong-ai-pin.png';
import FilmResearchPin from '../../assets/pins/film-research-pin.png';
import MagePin from '../../assets/pins/mage-pin.png';
import RcCarPin from '../../assets/pins/rc-car-pin.png';
import HappyEndingPin from '../../assets/pins/happy-ending-pin.png';
import type { BoardSide, PinConfig } from './types';

export const boardPins: Record<BoardSide, PinConfig[]> = {
  work: [
    {
      id: 'azure',
      image: AzurePin,
      size: 'md',
      initialRotate: 6,
      hoverRotate: -2,
      anchor: { left: 'clamp(34px, 7vw, 108px)', top: 'clamp(134px, 20vh, 178px)' },
      title: 'Azure Commerce',
      eyebrow: 'Professional',
      year: '2020 - 2021',
      subtitle: 'Commerce billing & rating infrastructure',
      description: 'Built and hardened Azure commerce billing and rating infrastructure across global and sovereign cloud environments, where correctness, compliance, and reliability directly impact customer invoices.',
      bullets: ['Delivered compliant billing and rating for customers in highly regulated, isolated cloud environments', 'Designed pricing and benefit data processing to keep per-customer charges accurate at scale', 'Hardened pipelines and automated recovery to improve reliability and cut manual operational effort'],
    },
    {
      id: 'xbox',
      image: XboxPin,
      size: 'md',
      initialRotate: 10,
      hoverRotate: 5,
      anchor: { right: 'clamp(52px, 8vw, 128px)', bottom: 'clamp(72px, 10vh, 118px)' },
      title: 'Xbox Store',
      eyebrow: 'Professional',
      year: '2021 - Present',
      subtitle: 'Full-stack owner of next-gen Xbox storefronts',
      description: 'Own the Xbox Console Store end to end and help drive next-gen Xbox storefronts across console, PC, and web, where reliability, performance, and polish directly shape how players discover and buy.',
      bullets: ['Own the Xbox Console Store end to end, from service integration to player-facing UI', 'Drive next-gen storefront architecture and commerce flows across console, PC, and web', 'Lead high-visibility launch readiness and storefront compliance for player-facing experiences', 'Trusted cross-team technical lead through reviews, launch support, and platform decisions'],
    },
  ],
  research: [
    {
      id: 'paper',
      image: FilmResearchPin,
      size: 'md',
      initialRotate: -8,
      hoverRotate: -3,
      anchor: { left: 'clamp(34px, 7vw, 112px)', top: 'clamp(158px, 24vh, 216px)' },
      title: 'ICCV Oral Paper',
      eyebrow: 'Academia',
      year: '2019',
      subtitle: 'A Graph-Based Framework to Bridge Movies and Synopses',
      description: "Contributed to an ICCV Oral research project aligning movie segments with synopsis paragraphs across 328 films. Built tooling and preprocessing support for reviewing temporal alignment data.",
      bullets: ['Contributed to graph-based temporal alignment pipeline', 'Built React/Flask annotator for cross-platform dataset review', 'Implemented motion-energy preprocessing for segments and keyframes'],
      link: 'https://openaccess.thecvf.com/content_ICCV_2019/papers/Xiong_A_Graph-Based_Framework_to_Bridge_Movies_and_Synopses_ICCV_2019_paper.pdf',
      linkLabel: 'Read paper',
    },
    {
      id: 'mahjong',
      image: MahjongAiPin,
      size: 'sm',
      initialRotate: 6,
      hoverRotate: -2,
      anchor: { right: 'clamp(58px, 9vw, 142px)', top: 'clamp(120px, 18vh, 164px)' },
      title: 'Suphx Mahjong AI',
      eyebrow: 'Research',
      year: 'Summer 2017',
      subtitle: "The World's Strongest Mahjong AI",
      description: 'Contributed to early Suphx research, a Mahjong AI system that reached top-level performance in imperfect-information gameplay. Focused on reinforcement learning support workflows and analysis tools.',
      bullets: ['Researched reinforcement learning strategies for imperfect-information play', 'Built Qt tooling to inspect game logs and model decisions', 'Supported analysis workflows for a top-performing Mahjong AI system'],
      link: 'https://www.microsoft.com/en-us/research/project/suphx-mastering-mahjong-with-deep-reinforcement-learning/',
      linkLabel: 'View research',
    },
    {
      id: 'ironman',
      image: RcCarPin,
      size: 'md',
      initialRotate: -4,
      hoverRotate: 2,
      anchor: { right: 'clamp(44px, 7vw, 118px)', bottom: 'clamp(72px, 10vh, 118px)' },
      title: 'IRONMAN',
      eyebrow: 'Applied Research',
      year: '2020',
      subtitle: 'VR remote-driving rig',
      description: 'Built a VR remote-driving prototype for ROAR/Berkeley research, streaming camera feeds into an Oculus headset and translating wheel/pedal input into vehicle steering commands through a Jetson Nano.',
      bullets: ['Integrated RealSense and CSI camera streams into a Unity/Oculus rig', 'Mapped Logitech wheel and pedal input to remote vehicle controls', 'Demonstrated teleoperation workflow for training, data collection, and autonomy testing'],
      link: 'https://roar.berkeley.edu/',
      linkLabel: 'Visit project',
    },
  ],
  play: [
    {
      id: 'killstreak',
      image: MagePin,
      size: 'md',
      initialRotate: 7,
      hoverRotate: 2,
      anchor: { left: 'clamp(42px, 8vw, 128px)', top: 'clamp(142px, 21vh, 190px)' },
      title: 'KillStreak',
      eyebrow: 'College Project',
      year: '2019',
      subtitle: 'OpenGL MOBA with custom networking and physics',
      description: 'Built a team-based OpenGL MOBA for UCSD CSE 125, focused on real-time multiplayer gameplay, custom physics, and client-side rendering prediction.',
      bullets: ['Implemented coarse-mesh collision to improve server tick performance', 'Built screen-to-world mouse movement and client-side prediction', 'Contributed abilities, economy, UI, and pre-match gameplay systems'],
      link: 'https://github.com/roystormstout/cse125-sp19-group3',
      linkLabel: 'View code',
    },
    {
      id: 'happyEnding',
      image: HappyEndingPin,
      size: 'sm',
      initialRotate: -8,
      hoverRotate: -2,
      anchor: { right: 'clamp(54px, 9vw, 136px)', bottom: 'clamp(78px, 11vh, 124px)' },
      title: 'A Happy Ending',
      eyebrow: 'VR Game',
      year: '2018',
      subtitle: 'Polished all-campus VR competition winner',
      description: 'Built an award-winning Oculus VR narrative game for an all-campus competition, focusing on player locomotion, environmental interactions, and scripted story events.',
      bullets: ['Won Most Polished and Best Sound Effects', 'Implemented Oculus locomotion and interaction systems', 'Built trigger-driven doors, event scripting, and chaptered narrative flow'],
      link: 'https://github.com/roystormstout/A_Happy_Ending_VR_Game',
      linkLabel: 'View code',
    },
  ],
};